# Fist target is the default target
# $@ == target
# $^ == dependancies of the rule
# create a wildcard variable
#

include config.mk

.PHONY : outdir
outdir: 
	mkdir -p $(outdir)


# reads file names
R1=$(basename $1)
R2=$(basename $2)

#PATH_TO_READS_FILE="coucou"
FASTQ_FILES=$(wildcard $(PATH_TO_READS_FILE)/*.fastq)

# Phony target, no target created but use @echo (and not echo to avoir printing the command)  and the TXT_FILES variables to print all matching patterns
## variables: print variables 
.PHONY : variables
variables :
		@echo TXT_FILES: $(FASTQ_FILES)
		@echo PATH: $(PATH_TO_READS_FILE)

.PHONY : load
load: 	
		module load system/python/2.7.9/
		module load bioinfo/cutadapt/default/
		module load compiler/gcc/4.9.2
		module load bioinfo/bwa/0.7.12
		module load bioinfo/samtools/1.3
		module load system/java/jre8
		module load bioinfo/picard-tools/1.130
		module load bioinfo/ncbi-blast/2.2.30


TXT_FILES=$(wildcard books/*.txt)
DAT_FILES=$(patsubst books/%.txt, %.dat, $(TXT_FILES))
PLOT_FILES=$(patsubst %.dat, %.png, $(DAT_FILES))

# program names variables
#
COUNT_SRC=wordcount.py
COUNT_EXE=python $(COUNT_SRC)

ZIP_SRC=zipf_test.py
ZIP_EXE=python $(ZIP_SRC)

PLOT_SRC=plotcount.py
PLOT_EXE=python $(PLOT_SRC)


# All variables can be contained in config file
# include a file that contain variable definition (src and exe)
#include config.mk

.PHONY : all
all : $(PLOT_FILES) results.txt


## results.txt : Generate zipf summary table
results.txt: $(DAT_FILES)  $(ZIP_SRC)
	$(ZIP_EXE) *.dat  > $@


## pngs: Generate png files from dat files 
.PHONY : pngs
pngs : $(PLOT_FILES)

%.png : $(DAT_FILES) $(PLOT_SRC)
		$(PLOT_EXE) $< $*.png


## dats : Generates wordcount of text files
.PHONY : dats
dats : $(DAT_FILES)
#count words.
%.dat : books/%.txt $(COUNT_SRC)
		$(COUNT_EXE) $< $*.dat



#
## Phony target, no target created but use @echo (and not echo to avoir printing the command)  and the TXT_FILES variables to print all matching patterns
### variables: print variables 
#.PHONY : variables
#variables :
#		@echo TXT_FILES: $(TXT_FILES)
#		@echo DAT_FILES: $(DAT_FILES)
#		@echo PLOT_FILES: $(PLOT_FILES)
#
.PHONY : help
help: Makefile
		@sed -n 's/^##//p' $<

#
#isles.dat : books/isles.txt wordcount.py
#	        python wordcount.py $< $@
#abyss.dat : books/abyss.txt wordcount.py
#	        python wordcount.py $< $@
#last.dat : books/last.txt wordcount.py
#	        python wordcount.py $< $@
# A phony target permit to execute a rule without a target. clean is not a target, it's the container of a  rule
## clean : clean autogenerated files
.PHONY: clean
clean :
	        rm -f $(DAT_FILES) $(PLOT_FILES)  results.txt


